### ISSUE TITLE
Can't re-open menu

### ISSUE THREAD

**Issue by Kevintjuhz** [ESX-PUBLIC/esx_securitycam#2]
When I look at the camera's and press backspace I exit the menu. But when I want to look into the cameras again The option to press 'e' doesn't pop up.

**Comment by LifeGoal** [comment]
Go out of the marker and then in to it again.

**Comment by Kevintjuhz** [comment]
T

Verstuurd vanaf mijn iPhone

**Comment by Kevintjuhz** [comment]
Ofcourse I tried that. But it doesn't seem to work. When I go to the scan for virus marker and press it. Then walk back to the Camera marker it works again.

**Comment by MpLLLL71** [comment]
Same issue too!

**Comment by Kamorak** [comment]
Same
