### ISSUE TITLE
Restart resource

### ISSUE THREAD

**Issue by parintele** [ESX-PUBLIC/esx_securitycam#6]
When I spawn for first time after srv rr, gotta restart the resource manually.
After using one of the cameras, gotta restart the resource again to be usable. ->Won't let me log into system again.

**Comment by LifeGoal** [comment]
I've personally never had this issue. We are using this script on Made For Sweden here in Sweden and it's working very well. Do you have any errors? Any more information?

**Comment by parintele** [comment]
I don't get any errors in console or anything. I just restart resource, then works. But after using it gotta restart again. strange anyway

**Comment by LifeGoal** [comment]
Should be fixed now.

**Comment by MpLLLL71** [comment]
I have the same issue actually

**Comment by LifeGoal** [comment]
Found a problem. Will update the resource soon!
