### ISSUE TITLE
Add to police menu ? 

### ISSUE THREAD

**Issue by zelizz** [ESX-PUBLIC/esx_securitycam#8]
hey, nice work ! 
How could I add it to police ? I know for the menu side but cant find what function I have to register and trigger :/

Thx u for any help and for your awesome work @LifeGoal !

**Comment by LifeGoal** [comment]
The script is old and the code is made very poorly. So it has no triggers really. It’s instant when you press E in the marker and it does not trigger any event or function when you press E. So you could add a event or function that you trigger from the police menu. I will recode this in the summer probably so it will get better!
